apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-apache-deployment
  namespace: application
  labels:
    app: custom-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-apache
  template:
    metadata:
      labels:
        app: custom-apache
    spec:
      containers:
      - name: custom-apache
        image: 891377137882.dkr.ecr.us-east-1.amazonaws.com/my-django-todo-app:latest
        ports:
        - containerPort: 80
