apiVersion: v1
kind: Service
metadata:
  name: custom-apache-service
  namespace: application
  labels:
    app: custom-apache
spec:
  type: NodePort  # Set the service type to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Specify the NodePort value
    protocol: TCP
    name: http
  selector:
    app: custom-apache
